use_frameworks!

platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'FFTableView_Example' do
  pod 'FFTableView', :path => '../'

  target 'FFTableView_Tests' do
    inherit! :search_paths

    
  end
end
